#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#

grpc:
  channels:
    todo-server:
      host: localhost
      port: 1408
      # host: todo-grpc.microk8s
      # port: 80

coherence:
  sessions:
    - name: default
      serializer: pof
      channel: todo-server
