#
# Copyright (c) 2021, 2022 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: todo-list
spec:
  cluster: todo-list
  replicas: 1
  image: ghcr.io/coherence-community/todo-list-spring-server:24.09
  imagePullPolicy: Always
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger-collector:4317"
  application:
    type: java
  coherence:
    metrics:
      enabled: true
#    persistence:
#      mode: active
#      persistentVolumeClaim:
#        storageClassName: "oci-bv"
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 50Gi
  jvm:
    memory:
      heapSize: 1g
  ports:
    - name: grpc
      port: 1408
    - name: http
      port: 3000
      serviceMonitor:
        enabled: true
    - name: metrics
      serviceMonitor:
        enabled: true
