apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  todo-http-ingress
spec:
  prefix: /
  service: todo-http:7001
  timeout_ms: 0
  idle_timeout_ms: 0
  listener_idle_timeout: 0
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: todo-grpc-ingress
spec:
  grpc: true
  prefix: /examples.ToDoList/
  rewrite: /examples.ToDoList/
  service: todo-grpc:1408
  timeout_ms: 0
  idle_timeout_ms: 0
  listener_idle_timeout: 0
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: coherence-grpc-ingress
spec:
  grpc: true
  prefix: /coherence.NamedCacheService/
  rewrite: /coherence.NamedCacheService/
  service: todo-grpc:1408
  timeout_ms: 0
  idle_timeout_ms: 0
  listener_idle_timeout: 0
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: reflection-grpc-ingress
spec:
  grpc: true
  prefix: /grpc.reflection.v1alpha.ServerReflection/
  rewrite: /grpc.reflection.v1alpha.ServerReflection/
  service: todo-grpc:1408
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: health-grpc-ingress
spec:
  grpc: true
  prefix: /grpc.health.v1.Health/
  rewrite: /grpc.health.v1.Health/
  service: todo-grpc:1408
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  todo-jaeger-ingress
spec:
  host: todo-jaeger.microk8s
  prefix: /
  service: jaeger-query:16686
  timeout_ms: 0
  idle_timeout_ms: 0
  listener_idle_timeout: 0
