micronaut:
  application:
    name: todo-list-micronaut-server
  server:
    port: 3000
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:web"

coherence:
  cluster: task-cluster
  ttl: 0
  serializer: pof
  distributed:
    localstorage: true
  grpc:
    server:
      port: 1408

graphql:
  enabled: true
  path: /graphql
  graphiql.enabled: true