#
# Copyright (c) 2024 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#

micronaut:
  application:
    name: todo-list-micronaut-server
  server:
    port: 7001
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:web"

coherence:
  cluster: task-cluster
  ttl: 0
  wka: localhost
  serializer: pof
  distributed:
    localstorage: true
  grpc:
    server:
      port: 1408
  data:
    tasks:
  tracing:
    ratio: 0

graphql:
  enabled: true
  path: /graphql
  graphiql.enabled: true