micronaut:
  application:
    name: todo-list-micronaut-server
  server:
    port: 3000
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:web"
graphql:
  enabled: true
  path: /graphql
  graphiql.enabled: true