# Copyright 2024 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence ToDo List Example GitHub Actions Scheduled Trivy Scan
# ---------------------------------------------------------------------------
name: Scheduled Trivy Scan

on:
  workflow_dispatch:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install local test-common artifact
        env:
          MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3
        run: mvn -B -pl test-common install --file java/pom.xml -s java/.mvn/settings.xml -DskipTests

      - name: Resolve Maven dependencies for Trivy
        env:
          MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3
        run: mvn -B dependency:resolve dependency:resolve-plugins -am --file java/pom.xml -s java/.mvn/settings.xml

      - name: Run Trivy vulnerability scanner to scan repo
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4  # aquasecurity/trivy-action@v0.32.0
        with:
          scan-type: 'fs'
          version: 'v0.71.0'
          scanners: 'vuln'
          exit-code: 1
          timeout: '15m'
          trivy-config: .github/trivy.yaml
